openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: '0.1'
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /v1/message:
    post:
      description: Create a new message
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewMessage"
            examples:
              '0':
                value: '{"message":"Hello World!"}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/message/{id}:
    get:
      description: Get a message by ID
      parameters:
        - name: id
          in: path
          description: ID of message to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewMessage:
      required:
        - message
      properties:
        message:
          type: string
          description: message to create
    Message:
      required:
        - id
        - message
      properties:
        id:
          type: integer
          format: int32
          description: Message ID
        message:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
