openapi: 3.0.1
info:
  title: Namer
  description: Namer description
  version: '0.0.1'
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /v1/name:
    get:
      description: Get names from a given year
      parameters:
        - name: year
          in: query
          description: the year of the name
          required: false
          schema:
            type: integer
            format: int64
          examples:
            '0':
              value: '2019'
        - name: page
          in: query
          description: the page number
          required: false
          schema:
            type: integer
            format: int64
          examples:
            '0':
              value: '1'
        - name: limit
          in: query
          description: the number of items per page
          required: false
          schema:
            type: integer
            format: int64
          examples:
            '0':
              value: '10'
      responses:
        '200':
          description: name response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamesPageResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/name/{id}:
    get:
      description: Get a name by ID
      parameters:
        - name: year
          in: query
          description: the year of the name
          required: false
          schema:
            type: integer
            format: int64
          examples:
            '0':
              value: '2019'
        - name: id
          in: path
          description: ID of message to return
          required: true
          schema:
            type: integer
            format: int64
          examples:
            '0':
              value: '1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameEntry'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NamesPageResponse:
      required:
        - names
        - year
        - page
        - limit
        - total
      properties:
        names:
          type: array
          items:
            $ref: '#/components/schemas/NameEntry'
          description: the names
        page:
          type: integer
          format: int64
          description: the page number
        year:
          type: integer
          format: int64
          description: the year of the names
        limit:
          type: integer
          format: int64
          description: the number of items per page
        total:
          type: integer
          format: int64
          description: the total number of items
    NameEntry:
      properties:
        name:
          type: string
          description: the name
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
