openapi: 3.0.1
info:
  title: Namer
  description: Namer description
  version: '0.0.1'
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /v1/name:
    get:
      description: Get names from a given year
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NamesPageRequest"
            examples:
              '0':
                value: '{"year":2019,"page":1,"limit":10}'
      responses:
        '200':
          description: name response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamesPageResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/name/{id}:
    get:
      description: Get a name by ID
      parameters:
        - name: id
          in: path
          description: ID of message to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NameEntry'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NamesRequest:
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
          description: the id of the name
    NamesPageRequest:
      properties:
        year:
          type: integer
          format: int32
          description: the year of the name
        page:
          type: integer
          format: int32
          description: the page number
        limit:
          type: integer
          format: int32
          description: the number of items per page
    NamesPageResponse:
      required:
        - names
        - page
        - limit
        - total
      properties:
        names:
          type: array
          items:
            $ref: '#/components/schemas/NameEntry'
          description: the names
        page:
          type: integer
          format: int32
          description: the page number
        limit:
          type: integer
          format: int32
          description: the number of items per page
        total:
          type: integer
          format: int32
          description: the total number of items
    NameEntry:
      properties:
        name:
          type: string
          description: the name
    Error:
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
